Fix display of host details when cpu_info is empty
If a Blazar host was created with an empty cpu_info value, displaying
host details would fail with the error:

    SyntaxError: unexpected EOF while parsing (<string>, line 0)

This is because calling eval() on an empty string raises a SyntaxError.
This patch ensures that if cpu_info is empty, it is set to an empty
dictionary instead.

Change-Id: I38d9f92fd7937de4ec1492d06ddea834b6c423ef